sudo: required
dist: trusty

language: php
php:
  - '5.6'

services:
  - mysql

before_install:
  - nvm install node
  - node --version
  - npm install -g npm@latest grunt-cli
  - npm install
  - mysql -e 'create database mojrokovnik;'
  - git clone https://github.com/mojrokovnik/mojrokovnik-server.git

install:
  - cd mojrokovnik-server
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php bin/console doctrine:schema:update --force
  - php bin/console fos:user:create admin admin@admin.com admin
  - php bin/console server:run localhost:8000 &
  - sleep 1
  - cd ..
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install
  - grunt build

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)
